#!/bin/bash
useradd client
passwd client
mv dbth.py sui.py si.py Rail.py serverslist gateways /root
apt-get install rssh
chsh -s /usr/bin/rssh client
apt-get install openvpn
printf "dev tun\nport 1194\nproto tcp\nserver 10.1.0.0 255.255.255.0\ncipher server1\ncipher AES-128-CBC\n\ntopology subnet\npush \"redirect-gateway bypass-dhcp bypass-dns\"\npersist-key\npersist-tun\nkeepalive 10 60\nduplicate-cn\ndh pki/dh.pem\nca pki/ca.crt\ncert pki/issued/server.crt\nkey pki/private/server.key\nremote-cert-tls client\nuser nobody\npush \"dhcp-option DNS 1.1.1.1\"" > server.conf
sysctl -w net.ipv4.ip_forward=1
ip rule add from 212.24.100.71 table 128
ip route add table 128 to 255.255.255.255 dev ens3
ip route add table 128 default via 169.254.0.1
iptables -t nat -A POSTROUTING -s 10.1.0.0/24 -j MASQUERADE
iptables-save > /etc/iptables/rules.v4
apt-get install git
apt-get update
cd
git clone https://github.com/OpenVPN/easy-rsa.git
cd ~/easy-rsa/easyrsa3
./easyrsa init-pki
./easyrsa build-ca
./easyrsa gen-crl
./easyrsa gen-req server
./easyrsa import-req server.req server
./easyrsa sign-req server server
./easyrsa gen-dh
mv pki /root
apt-get install python-pip
apt-get install python3-pip
pip install pexpect
pip install --upgrade pip
pip3 install pexpect
pip3 install --upgrade pip3
mkdir /home/client

